name: guitar_eik
description: A new Flutter project.

publish_to: none

version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shimmer: ^3.0.0
  rxdart: ^0.28.0
  flutter_dotenv: ^5.1.0
  faker: ^2.1.0
  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.6
  shared_preferences: ^2.5.5
  flutter_chord: ^0.1.2
  flutter_guitar_tabs: ^0.0.10
  google_fonts: ^8.0.2
  lottie: ^3.3.3
  dio: ^5.9.2
  flutter_skeleton_ui: ^0.0.6
  flutter_native_splash: ^2.4.7
  connectivity_plus: ^7.1.1

flutter_native_splash:
  color: "#A3A3A3"
  image: assets/images/logo.png
  color_dark: "#121212"
  image_dark: assets/images/logo_dark.png

  android_12:
    color: "#A3A3A3"
    image: assets/images/logo.png

    color_dark: "#121212"
    image_dark: assets/images/logo_dark.png
  fullscreen: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
  change_app_package_name: ^1.1.0
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
